// Code generated by go-swagger; DO NOT EDIT.

// Package restapi gophers-api
//
//	HTTP server that handle cute Gophers.
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 0.1.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//	  - text/plain
//
// swagger:meta
package restapi
