// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteGopherOKCode is the HTTP code returned for type DeleteGopherOK
const DeleteGopherOKCode int = 200

/*
DeleteGopherOK OK

swagger:response deleteGopherOK
*/
type DeleteGopherOK struct {
}

// NewDeleteGopherOK creates DeleteGopherOK with default headers values
func NewDeleteGopherOK() *DeleteGopherOK {

	return &DeleteGopherOK{}
}

// WriteResponse to the client
func (o *DeleteGopherOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteGopherNotFoundCode is the HTTP code returned for type DeleteGopherNotFound
const DeleteGopherNotFoundCode int = 404

/*
DeleteGopherNotFound A gopher with the specified Name was not found.

swagger:response deleteGopherNotFound
*/
type DeleteGopherNotFound struct {
}

// NewDeleteGopherNotFound creates DeleteGopherNotFound with default headers values
func NewDeleteGopherNotFound() *DeleteGopherNotFound {

	return &DeleteGopherNotFound{}
}

// WriteResponse to the client
func (o *DeleteGopherNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
