// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteGopherHandlerFunc turns a function with the right signature into a delete gopher handler
type DeleteGopherHandlerFunc func(DeleteGopherParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteGopherHandlerFunc) Handle(params DeleteGopherParams) middleware.Responder {
	return fn(params)
}

// DeleteGopherHandler interface for that can handle valid delete gopher params
type DeleteGopherHandler interface {
	Handle(DeleteGopherParams) middleware.Responder
}

// NewDeleteGopher creates a new http.Handler for the delete gopher operation
func NewDeleteGopher(ctx *middleware.Context, handler DeleteGopherHandler) *DeleteGopher {
	return &DeleteGopher{Context: ctx, Handler: handler}
}

/*
	DeleteGopher swagger:route DELETE /gopher deleteGopher

Delete a gopher by a given name
*/
type DeleteGopher struct {
	Context *middleware.Context
	Handler DeleteGopherHandler
}

func (o *DeleteGopher) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteGopherParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
