// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/scraly/gophers-api/pkg/swagger/server/models"
)

// GetGopherOKCode is the HTTP code returned for type GetGopherOK
const GetGopherOKCode int = 200

/*
GetGopherOK A gopher

swagger:response getGopherOK
*/
type GetGopherOK struct {

	/*
	  In: Body
	*/
	Payload *models.Gopher `json:"body,omitempty"`
}

// NewGetGopherOK creates GetGopherOK with default headers values
func NewGetGopherOK() *GetGopherOK {

	return &GetGopherOK{}
}

// WithPayload adds the payload to the get gopher o k response
func (o *GetGopherOK) WithPayload(payload *models.Gopher) *GetGopherOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get gopher o k response
func (o *GetGopherOK) SetPayload(payload *models.Gopher) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGopherOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetGopherNotFoundCode is the HTTP code returned for type GetGopherNotFound
const GetGopherNotFoundCode int = 404

/*
GetGopherNotFound A gopher with the specified Name was not found.

swagger:response getGopherNotFound
*/
type GetGopherNotFound struct {
}

// NewGetGopherNotFound creates GetGopherNotFound with default headers values
func NewGetGopherNotFound() *GetGopherNotFound {

	return &GetGopherNotFound{}
}

// WriteResponse to the client
func (o *GetGopherNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
