// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostGopherCreatedCode is the HTTP code returned for type PostGopherCreated
const PostGopherCreatedCode int = 201

/*
PostGopherCreated Created

swagger:response postGopherCreated
*/
type PostGopherCreated struct {
}

// NewPostGopherCreated creates PostGopherCreated with default headers values
func NewPostGopherCreated() *PostGopherCreated {

	return &PostGopherCreated{}
}

// WriteResponse to the client
func (o *PostGopherCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}
