// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/scraly/gophers-api/pkg/swagger/server/models"
)

// PostGopherOKCode is the HTTP code returned for type PostGopherOK
const PostGopherOKCode int = 200

/*
PostGopherOK Created

swagger:response postGopherOK
*/
type PostGopherOK struct {

	/*
	  In: Body
	*/
	Payload *models.Gopher `json:"body,omitempty"`
}

// NewPostGopherOK creates PostGopherOK with default headers values
func NewPostGopherOK() *PostGopherOK {

	return &PostGopherOK{}
}

// WithPayload adds the payload to the post gopher o k response
func (o *PostGopherOK) WithPayload(payload *models.Gopher) *PostGopherOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post gopher o k response
func (o *PostGopherOK) SetPayload(payload *models.Gopher) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostGopherOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
